### ISSUE TITLE
Object selection not working on petition list block 

### ISSUE THREAD

**Issue by AmnestyAM** [amnestywebsite/humanity-petitions#13]
![image](https://github.com/user-attachments/assets/2e43e185-4429-4486-b705-737007809e97)

**Comment by AmnestyAM** [comment]
yeah the spacing, I will check if thats the issue, thanks 
![image](https://github.com/user-attachments/assets/3238557f-f885-4a8c-92cf-1520a1e3c68c)

**Comment by AmnestyAM** [comment]
ahhh it also looks the the plus button is missing

**Comment by jaymcp** [comment]
It's there, it's just difficult to see because the item is so large. I have a fix in PR for the visual appearance, so perhaps it's worth waiting on that hitting STG first?

**Comment by jaymcp** [comment]
@AmnestyAM the visual fix is now available on STG
